### ISSUE TITLE
Little bit of context

### ISSUE THREAD

**Issue by marcoroganovic** [aishikaty/tiny-bind#1]
Hi, you have really nice collection of lightweight libraries. Can you tell me more about this one?

**Comment by aishikaty** [comment]
Hi @marcoroganovic, thank you.
This one is inspired by [transparency](http://leonidas.github.io/transparency/) with template syntax borrowed from [vue.js](https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand).
It's written mostly for educational purposes but maybe it could turn into something useful, who knows.
Also I've been experimenting with some tiny reactive UI libraries lately (like [this](https://github.com/danculley/real-dom) or [this](https://redom.js.org/)) and although those have nice data binding in place I'm missing separation of HTML and JS code in them so this library could potentially fill the gap.

**Comment by marcoroganovic** [comment]
Nice, I wanted to say that looks like templating engine but maybe I was missing the point. Thanks for clarifying. It good to hear that you're writing this for educational purposes, I also tend to do same. I saw your profile when I was re-searching how to implement iteration logic in HTML, but when I try to read code I often get lost in some regular expression. So, I'm wondering if you could tell me how you implemented it?

**Comment by aishikaty** [comment]
@marcoroganovic You're welcome. Sure I can, I will get back to you tomorrow because I'm going to bed now.

**Comment by aishikaty** [comment]
@marcoroganovic I implemented it using recursion, going from top element it reads template attributes, gets values for them by running eval in context of provided data object and sets the result values. The regular expression with /^on/ handles event listeners so it doesn't evaluate immediately but rather wraps the code to run in a callback.

After this is done for one element, it goes through the children and runs the same process for them.
There is also special case for when you provide array as the data object, it duplicates the element with el.cloneNode() and inserts it before the template element.

What is missing in the code right now is some kind of diffing algorithm for when you call the function second time, for now it only saves the template into el.__tinyBind so you can call the function again on the same element with different data.

**Comment by marcoroganovic** [comment]
Hey, thanks for explaining it thoroughly. You are doing pretty decent operation with such small amount of code. I wanted to implement something like this without using eval() but actually with some kind of parser, for instance JISON. This type of topics made me feel bad about not taking formal Computer Science courses.

I want to create something like [Monkberry](https://github.com/monkberry/monkberry). I don't know if you are familiar with it but I'm really amazed with this tiny library even though is not actively maintained.

**Comment by marcoroganovic** [comment]
I have one more question. Do you design public API before writing code? In the beginning I was literally programming by accident, I jumped straight to code editor, but now I use mentioned approach and I have to say that is much easier to think about problem.

**Comment by aishikaty** [comment]
@marcoroganovic You're welcome. Yes I've seen Monkberry before, it seems nice. I'm looking forward to see what you're going to make.

I do design API first. Sometimes just in my head but I tend to write example code of using a library before writing the actual library. Also related to that is [readme first](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html) approach I really like.

**Comment by marcoroganovic** [comment]
@aishikaty thank you for taking time to answer my questions. This link is great, also. Since both of us love open-source and lightweight libraries maybe we could build something together. Let me now if you are interested.

**Comment by aishikaty** [comment]
@marcoroganovic Yeah, that would be cool.

**Comment by marcoroganovic** [comment]
@aishikaty Great! Can you tell me in which timezone you are, and if you have some easier way for communication? Maybe Gitter or Slack...
